persistence true
persistence_location /mosquitto/data/
autosave_interval 10
log_dest stdout
listener 1883
allow_anonymous false
password_file /mosquitto/auth/passwords
acl_file /mosquitto/config/acl
max_queued_messages 1000
max_inflight_messages 20
message_size_limit 16384
max_packet_size 20000
persistent_client_expiration 1d
